apiVersion: v1
data:
  config.yaml: |
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
    # - hostname: tunnel55.umeshkhatiwada.com.np
    #   service: http://my-phpmyadmin:80
    - service: http_status:404
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    origincert: /etc/cloudflared/cert/origin-cert.pem
    tunnel: umeshdomain_np
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: default
  