apiVersion: apps/v1
kind: Deployment
metadata:
 name: cloudflared
spec:
 selector:
   matchLabels:
     app: cloudflared
 replicas: 1
 template:
   metadata:
     labels:
       app: cloudflared
   spec:
     containers:
     - name: cloudflared
       image: cloudflare/cloudflared:latest
       args:
       - tunnel
       - --config
       - /etc/cloudflared/config/config.yaml
       - run
       volumeMounts:
       - name: config
         mountPath: /etc/cloudflared/config
         readOnly: true
       - name: creds
         mountPath: /etc/cloudflared/creds
         readOnly: true
       - name: cert
         mountPath: /etc/cloudflared/cert
         readOnly: true
       resources:
         requests:
           memory: "64Mi"
           cpu: "250m"
         limits:
           memory: "128Mi"
           cpu: "500m"
     volumes:
     - name: creds
       secret:
         secretName: tunnel-credentials
     - name: config
       configMap:
         name: cloudflared
         items:
         - key: config.yaml
           path: config.yaml
     - name: cert
       secret:
         secretName: origin-cert

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-api-deployment
  labels:
    app: cloudflared-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-api
  template:
    metadata:
      labels:
        app: cloudflared-api
    spec:
      containers:
      - name: cloudflared-api
        image: umesh1212/cloudflared-api:tag5
        ports:
        - containerPort: 8081