apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: update-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-secrets-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: update-secrets
  apiGroup: rbac.authorization.k8s.io
